### ISSUE TITLE
Can we build opencv and opencv_contrib separately in 2 steps?

### ISSUE THREAD

**Issue by jiapei100** [opencv/opencv_contrib#930]
##### System information (version)
- OpenCV => :3.2.0-dev:
- Operating System / Platform => :Ubuntu 16.04.1:
- Compiler => :GCC 5.4.0:

##### Detailed description
Trying to build opencv together with opencv_contrib, with configuration:                           
-DOPENCV_EXTRA_MODULES_PATH=xxxxxxxxxx

However, it always reports some Error message as what I posted here:
[https://github.com/opencv/opencv/issues/7939](https://github.com/opencv/opencv/issues/7939)

Just wonder if there is a way to build opencv and opencv_contrib separately? which seems to be more reasonable???

Thank you 
Pei

**Comment by alalek** [comment]
No, you can't.

**Comment by jiapei100** [comment]
@alalek 
However, for cnn_3dobj:
( refer to https://github.com/opencv/opencv_contrib/blob/master/modules/README.md )

cnn_3dobj: Deep Object Recognition and Pose -- Uses Caffe Deep Neural Net library to build, train and test a CNN model of visual object recognition and pose.


Caffe requires opencv, opencv_contrib is based on caffe.... This is a circle, isn't it?


Pei

**Comment by alalek** [comment]
It is resolved. But version should be the same to avoid conflicts.
You can build opencv without opencv_contrib, but you can't build opencv_contrib without opencv sources (yet).

BTW, gcc uses gcc to compile itself.

**Comment by jiapei100** [comment]
@alalek 
Does that mean: the best way to build a full package of opencv, including both opencv and opencv_contrib, is to build in the following sequence:

1. opencv
2. caffe
3. opencv_contrib
?

Thank you 
Pei

**Comment by alalek** [comment]
Probably yes, but it depends on details.

BTW, Caffe's dependency on OpenCV is [optional](https://github.com/BVLC/caffe/commit/f3a933a620b8b089a7fe29ba76ec27f5408ff68d), you need to check `USE_OPENCV` option.

**Comment by jiapei100** [comment]
@alalek 

Just tested again. 

opencv with Cuda Enabled successfully installed
caffe with Cuda Enabled successfully installed

opencv_contrib with Cuda Enabled, still the same issue as  [https://github.com/opencv/opencv/issues/7939](https://github.com/opencv/opencv/issues/7939) .
I even turn  **BUILD_opencv_cnn_3dobj** to **OFF** .


After I set all CUDA related options to OFF, including:
WITH_CUBLAS=OFF
WITH_CUDA=OFF
WITH_CUFFT=OFF
etc.
both opencv and opencv_contrib are NOW successfully built...


A phrasal conclusion NOW can be made as:
**There must be a conflict between CUDA 8.0.44 and opencv_contrib (git master)**

How can I dig into it a bit further?

Cheers
Pei

**Comment by alalek** [comment]
Check files owner in your build directory - it may be a problem if you run `sudo make install` or similar.

**Comment by jiapei100** [comment]
@alalek 

No, I **DONOT** use **sudo make install** 
Most of the time, I use cmake in this way:

```
ccmake ../
make -j8
sudo checkinstall ...
```

Further suggestions?

**Comment by alalek** [comment]
`sudo` breaks access right of your build sub-folders, so regular `make` command may fail.

I doesn't see error messages from your build log, so there is no other suggestions from me.

**Comment by jiapei100** [comment]
@alalek Problem solved on one of my desktops...

I believe it has something to do with VTK installed previously, which is based on a previous OpenCV. After upgrading to a new OpenCV, the dependencies messed up somewhere...

Thanks anyway
And, happy NEW year.

**Comment by jiapei100** [comment]
In addition, I did notice that cnn_3dobj relies on viz, which relies on VTK, which is supposed to be installed after OpenCV has been installed already... This seems to be a loop..

```
modules/viz/CMakeLists.txt:2:  ocv_module_disable(viz)
modules/viz/CMakeLists.txt:7:ocv_define_module(viz opencv_core ${VTK_LIBRARIES} WRAP python)
```

So, turn OFF **cnn_3dobj** seems to be a must...

Cheers
Pei
